/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAdmin;

import ViewAdmin.FTransaksiBKeluar;
import ViewAdmin.FTransaksiBMasuk;
import ViewAdmin.FormPelanggan;
import ViewAdmin.Login;
import ViewAdmin.FormBarang;
import Class.DatabaseConnection;
import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import ViewAdmin.GantiPassword;
import ViewAdmin.TambahPengguna;

/**
 *
 * @author Fauzan13
 */
public class MenuUtama extends javax.swing.JFrame {
    
String hakakses;
    /**
     * Creates new form MenuUtama
     */
    Connection koneksi;

    public MenuUtama() {
        initComponents();
        koneksi = (Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
        jDialog1.setPreferredSize(new Dimension(481, 332));
        jDialog1.setMinimumSize(new Dimension(481, 332));
        jDialog1.setMaximumSize(new Dimension(481, 332));
            jDialog1.setLocationRelativeTo(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMenuLogout();
    }
    
       private void setMenuLogout(){
        mnFB.setEnabled(true);
        jMenuItem18.setEnabled(true);
        mnFP.setEnabled(true);
        TPemB.setEnabled(true);
        TPenB.setEnabled(true);
        mnLogout.setEnabled(true);
        mnGantiPassword.setEnabled(true);
        mnTambahPengguna.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnFB1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnFP1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        TPemB1 = new javax.swing.JMenuItem();
        TPenB1 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        LprnBarangKeluar1 = new javax.swing.JMenuItem();
        LprnBarangMasuk1 = new javax.swing.JMenuItem();
        LprnPersediaan1 = new javax.swing.JMenuItem();
        LprnDaraBarang1 = new javax.swing.JMenuItem();
        Help1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        bLogin2 = new javax.swing.JButton();
        bBatal3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnFB = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnFP = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        TPemB = new javax.swing.JMenuItem();
        TPenB = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        LprnBarangKeluar = new javax.swing.JMenuItem();
        LprnBarangMasuk = new javax.swing.JMenuItem();
        LprnPersediaan = new javax.swing.JMenuItem();
        LprnBrngYangDijual = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Logout = new javax.swing.JMenu();
        mnGantiPassword = new javax.swing.JMenuItem();
        mnTambahPengguna = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem5.setText("jMenuItem5");

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        jMenu8.setText("Home");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Home");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuBar2.add(jMenu8);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Master.png"))); // NOI18N
        jMenu6.setText("Master");

        mnFB1.setText("Form Barang");
        mnFB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFB1ActionPerformed(evt);
            }
        });
        jMenu6.add(mnFB1);
        jMenu6.add(jSeparator2);

        mnFP1.setText("Form Pelanggan");
        mnFP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFP1ActionPerformed(evt);
            }
        });
        jMenu6.add(mnFP1);

        jMenuBar2.add(jMenu6);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi.png"))); // NOI18N
        jMenu9.setText("Transaksi");

        TPemB1.setText("Pembelian Barang");
        TPemB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPemB1ActionPerformed(evt);
            }
        });
        jMenu9.add(TPemB1);

        TPenB1.setText("Penjualan Barang");
        TPenB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPenB1ActionPerformed(evt);
            }
        });
        jMenu9.add(TPenB1);

        jMenuBar2.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        jMenu10.setText("Laporan");

        LprnBarangKeluar1.setText("Barang Keluar");
        LprnBarangKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBarangKeluar1ActionPerformed(evt);
            }
        });
        jMenu10.add(LprnBarangKeluar1);

        LprnBarangMasuk1.setText("Barang Masuk");
        LprnBarangMasuk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBarangMasuk1ActionPerformed(evt);
            }
        });
        jMenu10.add(LprnBarangMasuk1);

        LprnPersediaan1.setText("Persediaan Barang");
        LprnPersediaan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnPersediaan1ActionPerformed(evt);
            }
        });
        jMenu10.add(LprnPersediaan1);

        LprnDaraBarang1.setText("Data Barang");
        LprnDaraBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnDaraBarang1ActionPerformed(evt);
            }
        });
        jMenu10.add(LprnDaraBarang1);

        jMenuBar2.add(jMenu10);

        Help1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hepl.png"))); // NOI18N
        Help1.setText("Help");
        Help1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help1ActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Help");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Help1.add(jMenuItem8);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Help1.add(jMenuItem2);

        jMenuBar2.add(Help1);

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem15.setText("jMenuItem15");

        jMenuItem16.setText("jMenuItem16");

        jPanel1.setBackground(new java.awt.Color(27, 31, 46));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        bLogin2.setBackground(java.awt.Color.cyan);
        bLogin2.setForeground(new java.awt.Color(255, 255, 255));
        bLogin2.setText("Login");
        bLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogin2ActionPerformed(evt);
            }
        });

        bBatal3.setBackground(new java.awt.Color(255, 0, 0));
        bBatal3.setForeground(new java.awt.Color(255, 255, 255));
        bBatal3.setText("Cancel");
        bBatal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatal3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bBatal3)
                        .addGap(18, 18, 18)
                        .addComponent(bLogin2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin2)
                    .addComponent(bBatal3))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pt anugrah jaya (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1704, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jMenuBar3.setBackground(new java.awt.Color(255, 255, 255));

        jMenu11.setBackground(new java.awt.Color(255, 255, 255));
        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        jMenu11.setText("Home");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });
        jMenuBar3.add(jMenu11);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Master.png"))); // NOI18N
        jMenu3.setText("Master");

        mnFB.setBackground(new java.awt.Color(255, 255, 255));
        mnFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/barang1.jpg"))); // NOI18N
        mnFB.setEnabled(false);
        mnFB.setText("Form Barang");
        mnFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFBActionPerformed(evt);
            }
        });
        jMenu3.add(mnFB);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/persediaanbarang.jpg"))); // NOI18N
        jMenuItem18.setText("Persediaan");
        jMenuItem18.setEnabled(false);
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);
        jMenu3.add(jSeparator1);

        mnFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/pelanggan.png"))); // NOI18N
        mnFP.setText("Form Pelanggan");
        mnFP.setEnabled(false);
        mnFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFPActionPerformed(evt);
            }
        });
        jMenu3.add(mnFP);

        jMenuBar3.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi.png"))); // NOI18N
        jMenu4.setText("Transaksi");

        TPemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/pembelian.jpg"))); // NOI18N
        TPemB.setEnabled(false);
        TPemB.setText("Pembelian Barang");
        TPemB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPemBActionPerformed(evt);
            }
        });
        jMenu4.add(TPemB);

        TPenB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/penjualan.jpg"))); // NOI18N
        TPenB.setEnabled(false);
        TPenB.setText("Penjualan Barang");
        TPenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPenBActionPerformed(evt);
            }
        });
        jMenu4.add(TPenB);

        jMenuBar3.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        jMenu5.setText("Laporan");

        LprnBarangKeluar.setText("Penjualan");
        LprnBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBarangKeluarActionPerformed(evt);
            }
        });
        jMenu5.add(LprnBarangKeluar);

        LprnBarangMasuk.setText("Pembelian");
        LprnBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBarangMasukActionPerformed(evt);
            }
        });
        jMenu5.add(LprnBarangMasuk);

        LprnPersediaan.setText("Persediaan Barang");
        LprnPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnPersediaanActionPerformed(evt);
            }
        });
        jMenu5.add(LprnPersediaan);

        LprnBrngYangDijual.setText("Data Barang");
        LprnBrngYangDijual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBrngYangDijualActionPerformed(evt);
            }
        });
        jMenu5.add(LprnBrngYangDijual);
        jMenu5.add(jSeparator4);

        jMenuItem17.setText("Pelanggan");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar3.add(jMenu5);

        Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hepl.png"))); // NOI18N
        Help.setText("Help");
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jMenuBar3.add(Help);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setting.png"))); // NOI18N
        Logout.setText("System");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        mnGantiPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/gantipassword.png"))); // NOI18N
        mnGantiPassword.setText("Ganti Password");
        mnGantiPassword.setEnabled(false);
        mnGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGantiPasswordActionPerformed(evt);
            }
        });
        Logout.add(mnGantiPassword);

        mnTambahPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/tambahpengguna.jpg"))); // NOI18N
        mnTambahPengguna.setText("Tambah Pengguna");
        mnTambahPengguna.setEnabled(false);
        mnTambahPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTambahPenggunaActionPerformed(evt);
            }
        });
        Logout.add(mnTambahPengguna);

        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/logout.png"))); // NOI18N
        mnLogout.setText("Logout");
        mnLogout.setEnabled(false);
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        Logout.add(mnLogout);

        jMenuBar3.add(Logout);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        MenuUtama m = new MenuUtama();
        m.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed

    }//GEN-LAST:event_jMenu8ActionPerformed

    private void mnFB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFB1ActionPerformed
        FormBarang fb = new FormBarang();
        fb.show();
    }//GEN-LAST:event_mnFB1ActionPerformed

    private void mnFP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFP1ActionPerformed
        FormPelanggan fp = new FormPelanggan();
        fp.show();
    }//GEN-LAST:event_mnFP1ActionPerformed

    private void TPemB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPemB1ActionPerformed
        FTransaksiBMasuk FTB = new FTransaksiBMasuk();
        FTB.show();
    }//GEN-LAST:event_TPemB1ActionPerformed

    private void TPenB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPenB1ActionPerformed
        FTransaksiBKeluar FTB = new FTransaksiBKeluar();
        FTB.show();
    }//GEN-LAST:event_TPenB1ActionPerformed

    private void LprnBarangKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBarangKeluar1ActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jrxml";
            reportDest = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBarangKeluar1ActionPerformed

    private void LprnBarangMasuk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBarangMasuk1ActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jrxml";
            reportDest = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBarangMasuk1ActionPerformed

    private void LprnPersediaan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnPersediaan1ActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jrxml";
            reportDest = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnPersediaan1ActionPerformed

    private void LprnDaraBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnDaraBarang1ActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jrxml";
            reportDest = System.getProperty("user.dir") + "/Report/Reportpeminjamanbuku.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnDaraBarang1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FHelp h = new FHelp();
        h.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Help1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help1ActionPerformed

    }//GEN-LAST:event_Help1ActionPerformed

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed

    }//GEN-LAST:event_jMenu11ActionPerformed

    private void mnFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFBActionPerformed
        FormBarang fb = new FormBarang();
        fb.show();
    }//GEN-LAST:event_mnFBActionPerformed

    private void mnFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFPActionPerformed
        FormPelanggan fp = new FormPelanggan();
        fp.show();
    }//GEN-LAST:event_mnFPActionPerformed

    private void TPemBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPemBActionPerformed
        FTransaksiBMasuk FTB = new FTransaksiBMasuk();
        FTB.show();
    }//GEN-LAST:event_TPemBActionPerformed

    private void TPenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPenBActionPerformed
        FTransaksiBKeluar FTB = new FTransaksiBKeluar();
        FTB.show();
    }//GEN-LAST:event_TPenBActionPerformed

    private void LprnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBarangKeluarActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportPenjualanBarang.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportPenjualanBarang.jasper";
            
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBarangKeluarActionPerformed

    private void LprnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBarangMasukActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportBarangMasuk.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportBarangMasuk.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBarangMasukActionPerformed

    private void LprnPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnPersediaanActionPerformed
        // TODO add your handling code here:
   String reportSource = null;
        String reportDest = null;
        
        try {
            
            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir")+ "/report/ReportPersediaan.jrxml";
            reportDest = System.getProperty("user.dir")+ "/report/ReportPersediaan.jasper";
            
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);
            
        }catch(Exception e){
            System.out.println(e);
            
                   
        }
    }//GEN-LAST:event_LprnPersediaanActionPerformed

    private void LprnBrngYangDijualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBrngYangDijualActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportDataBarang.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportDataBarang.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBrngYangDijualActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed

    }//GEN-LAST:event_HelpActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        dispose();
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGantiPasswordActionPerformed
        // TODO add your handling code here:
        GantiPassword  trsk1 = new GantiPassword();
        trsk1.show();
    }//GEN-LAST:event_mnGantiPasswordActionPerformed

    private void mnTambahPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTambahPenggunaActionPerformed
        // TODO add your handling code here:
        TambahPengguna  trsk1 = new TambahPengguna();
        trsk1.show();
    }//GEN-LAST:event_mnTambahPenggunaActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_LogoutActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        FPersediaanBarang fpb = new FPersediaanBarang();
        fpb.show();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportPelanggan.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportPelanggan.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
        // TODO add your handling code here:
        dispose();
        MenuUtama m = new MenuUtama();
        m.show();
    }//GEN-LAST:event_jMenu11MouseClicked

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseClicked
        // TODO add your handling code here:
        FHelp h = new FHelp();
        h.show();
    }//GEN-LAST:event_HelpMouseClicked
int ascii;
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        if (ascii==10) {
            try {
                Statement stmt = koneksi.createStatement();
                String query="select * from t_pengguna where username = '"+txtUsername.getText()+"'AND password = '"+txtPassword.getText()+"'";
                stmt=koneksi.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                if(rs.next()) {

                    JOptionPane.showMessageDialog(this, "Welcome To : " + txtUsername.getText() + "","Informasi",JOptionPane.INFORMATION_MESSAGE);

                    new MenuUtama().setVisible(true);

                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Identitas : " + txtUsername.getText() + " : Tidak diketahui!!!","Informasi",JOptionPane.ERROR_MESSAGE);
                    txtUsername.setText("");
                    txtPassword.setText("");
                    txtUsername.requestFocus();

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "gaggal login"+e.getMessage());

            }
        }
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        int ascii = evt.getKeyCode();
        if (ascii==10){
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void bLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogin2ActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_bLogin2ActionPerformed

    private void bBatal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatal3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bBatal3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Help;
    private javax.swing.JMenu Help1;
    private javax.swing.JMenu Logout;
    private javax.swing.JMenuItem LprnBarangKeluar;
    private javax.swing.JMenuItem LprnBarangKeluar1;
    private javax.swing.JMenuItem LprnBarangMasuk;
    private javax.swing.JMenuItem LprnBarangMasuk1;
    private javax.swing.JMenuItem LprnBrngYangDijual;
    private javax.swing.JMenuItem LprnDaraBarang1;
    private javax.swing.JMenuItem LprnPersediaan;
    private javax.swing.JMenuItem LprnPersediaan1;
    private javax.swing.JMenuItem TPemB;
    private javax.swing.JMenuItem TPemB1;
    private javax.swing.JMenuItem TPenB;
    private javax.swing.JMenuItem TPenB1;
    private javax.swing.JButton bBatal3;
    private javax.swing.JButton bLogin2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem mnFB;
    private javax.swing.JMenuItem mnFB1;
    private javax.swing.JMenuItem mnFP;
    private javax.swing.JMenuItem mnFP1;
    private javax.swing.JMenuItem mnGantiPassword;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnTambahPengguna;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
