/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAdmin;

import Class.DatabaseConnection;
import ViewUser.FPersediaanBarangUser;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import ViewUser.FTransaksiBKeluarUser;
import ViewUser.FTransaksiBMasukUser;
import ViewUser.FormBarangUser;
import ViewUser.FormPelangganUser;
import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import javax.swing.JFrame;
import ViewAdmin.Login;

/**
 *
 * @author Fauzan13
 */
public class MenuUtamaUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtamaUserUser
     */
    Connection koneksi;
    public MenuUtamaUser() {
        initComponents();
        setMenuLogout();
          initComponents();
        koneksi = (Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setMenuLogout(){
        mnFB.setEnabled(true);
        jMenuItem18.setEnabled(true);
        mnFP.setEnabled(true);
        TPemB.setEnabled(true);
        TPenB.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnFB = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnFP = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        TPemB = new javax.swing.JMenuItem();
        TPenB = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        LprnBarangKeluar = new javax.swing.JMenuItem();
        LprnBarangMasuk = new javax.swing.JMenuItem();
        LprnPersediaan = new javax.swing.JMenuItem();
        LprnBrngYangDijual = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pt anugrah jaya (2).png"))); // NOI18N

        jMenuBar3.setBackground(new java.awt.Color(255, 255, 255));

        jMenu11.setBackground(new java.awt.Color(255, 255, 255));
        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        jMenu11.setText("Home");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });
        jMenuBar3.add(jMenu11);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Master.png"))); // NOI18N
        jMenu3.setText("Master");

        mnFB.setBackground(new java.awt.Color(255, 255, 255));
        mnFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/barang1.jpg"))); // NOI18N
        mnFB.setText("Form Barang");
        mnFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFBActionPerformed(evt);
            }
        });
        jMenu3.add(mnFB);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/persediaanbarang.jpg"))); // NOI18N
        jMenuItem18.setText("Persediaan");
        jMenuItem18.setEnabled(false);
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);
        jMenu3.add(jSeparator1);

        mnFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/pelanggan.png"))); // NOI18N
        mnFP.setText("Form Pelanggan");
        mnFP.setEnabled(false);
        mnFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFPActionPerformed(evt);
            }
        });
        jMenu3.add(mnFP);

        jMenuBar3.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi.png"))); // NOI18N
        jMenu4.setText("Transaksi");

        TPemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/pembelian.jpg"))); // NOI18N
        TPemB.setText("Pembelian Barang");
        TPemB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPemBActionPerformed(evt);
            }
        });
        jMenu4.add(TPemB);

        TPenB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/penjualan.jpg"))); // NOI18N
        TPenB.setText("Penjualan Barang");
        TPenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPenBActionPerformed(evt);
            }
        });
        jMenu4.add(TPenB);

        jMenuBar3.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        jMenu5.setText("Laporan");

        LprnBarangKeluar.setText("Penjualan");
        LprnBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBarangKeluarActionPerformed(evt);
            }
        });
        jMenu5.add(LprnBarangKeluar);

        LprnBarangMasuk.setText("Pembelian");
        LprnBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBarangMasukActionPerformed(evt);
            }
        });
        jMenu5.add(LprnBarangMasuk);

        LprnPersediaan.setText("Persediaan Barang");
        LprnPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnPersediaanActionPerformed(evt);
            }
        });
        jMenu5.add(LprnPersediaan);

        LprnBrngYangDijual.setText("Data Barang");
        LprnBrngYangDijual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LprnBrngYangDijualActionPerformed(evt);
            }
        });
        jMenu5.add(LprnBrngYangDijual);
        jMenu5.add(jSeparator4);

        jMenuItem17.setText("Pelanggan");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar3.add(jMenu5);

        Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hepl.png"))); // NOI18N
        Help.setText("Help");
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jMenuBar3.add(Help);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu item/logout.png"))); // NOI18N
        jMenu1.setText("Logout");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu1);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1704, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
        // TODO add your handling code here:
dispose();
        MenuUtamaUser m = new MenuUtamaUser();
        m.show();
        setMenuLogout();
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed

    }//GEN-LAST:event_jMenu11ActionPerformed

    private void mnFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFBActionPerformed
        FormBarangUser fb = new FormBarangUser();
        fb.show();
    }//GEN-LAST:event_mnFBActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        FPersediaanBarangUser fpb = new FPersediaanBarangUser();
        fpb.show();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void mnFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFPActionPerformed
        FormPelangganUser fp = new FormPelangganUser();
        fp.show();
    }//GEN-LAST:event_mnFPActionPerformed

    private void TPemBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPemBActionPerformed
        FTransaksiBMasukUser FTB = new FTransaksiBMasukUser();
        FTB.show();
    }//GEN-LAST:event_TPemBActionPerformed

    private void TPenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPenBActionPerformed
        FTransaksiBKeluarUser FTB = new FTransaksiBKeluarUser();
        FTB.show();
    }//GEN-LAST:event_TPenBActionPerformed

    private void LprnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBarangKeluarActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportPenjualanBarang.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportPenjualanBarang.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBarangKeluarActionPerformed

    private void LprnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBarangMasukActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportBarangMasuk.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportBarangMasuk.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBarangMasukActionPerformed

    private void LprnPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnPersediaanActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir")+ "/report/ReportPersediaan.jrxml";
            reportDest = System.getProperty("user.dir")+ "/report/ReportPersediaan.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        }catch(Exception e){
            System.out.println(e);

        }
    }//GEN-LAST:event_LprnPersediaanActionPerformed

    private void LprnBrngYangDijualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LprnBrngYangDijualActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportDataBarang.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportDataBarang.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LprnBrngYangDijualActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {

            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_tokok");
            reportSource = System.getProperty("user.dir") + "/report/ReportPelanggan.jrxml";
            reportDest = System.getProperty("user.dir") + "/report/ReportPelanggan.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseClicked
        // TODO add your handling code here:
        FHelp h = new FHelp();
        h.show();
    }//GEN-LAST:event_HelpMouseClicked

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed

    }//GEN-LAST:event_HelpActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem LprnBarangKeluar;
    private javax.swing.JMenuItem LprnBarangMasuk;
    private javax.swing.JMenuItem LprnBrngYangDijual;
    private javax.swing.JMenuItem LprnPersediaan;
    private javax.swing.JMenuItem TPemB;
    private javax.swing.JMenuItem TPenB;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem mnFB;
    private javax.swing.JMenuItem mnFP;
    // End of variables declaration//GEN-END:variables
}
